Drop unreachable code during codegen
The semantic analysis pass will currently warn and fail if a literal is
provided to the `buf` function. This makes the code path that uses this literal
for the fixed buffer length non-functional, since it will only be executed if
length provided is smaller than the buffer anyways.

For example, if a larger value is provided:
```
bpftrace -e 'BEGIN { $x = buf(10, 1000); }'
stdin:1:14-27: WARNING: buf() length is too long and will be shortened to 64 bytes (see BPFTRACE_MAX_STRLEN)
BEGIN { $x = buf(10, 1000); }
             ~~~~~~~~~~~~~
WARNING: Addrspace is not set
error: <unknown>:0:0: in function BEGIN i64 (ptr): Looks like the BPF stack limit is exceeded. Please move large on stack variables into BPF per-cpu array map. For non-kernel uses, the stack can be increased using -mllvm -bpf-stack-size.
```